/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package icarius;

import java.io.IOException;

import okhttp3.Call;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class App {
    private static final String BASE_URL = "http://localhost:8080";

    OkHttpClient client = new OkHttpClient();

    public String sendPost() throws IOException {
        RequestBody formBody = new FormBody.Builder()
                                .add("name", "sentPost")
                                .add("apiKey", "adminKey")
                                .build();

        Request request = new Request.Builder()
                            .url(BASE_URL + "/api/campus/new")
                            .post(formBody)
                            .build();

        Call call = client.newCall(request);
        try (Response response = call.execute()) {
            return response.body().string();
        }
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().sendPost());
    }
}
