/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package icarius;

import java.util.HashMap;

import icarius.services.HttpService;
import okhttp3.ResponseBody;

public class App {
    private static final String BASE_URL = "http://localhost:8080";


    public App() {
        // TEST POST
        // create args list
        HashMap<String, String> args = new HashMap<String, String>();
        args.put("name", "test1");
        args.put("apiKey", "adminKey");
        // send post
        HttpService.post(BASE_URL + "/api/campus/new", args);


        // TEST GET
        ResponseBody response = HttpService.get(BASE_URL + "/api/birds/campus?campusId=10");
        System.out.println(response.toString());
    }

    public static void main(String[] args) {
       new App();
    }
}
